name: Build and Push Docker Image

on:
  push:
    branches: 
      - "main"
      - "**"  # This will match all other branches
  # Optionally, you can also trigger on pull requests
  # pull_request:
  #   branches: [ "main" ]

env:
  DOCKER_IMAGE_NAME: hevy-load  # Change this to your preferred image name

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:test
            ${{ github.ref == 'refs/heads/main' && format('{0}/{1}:latest', secrets.DOCKERHUB_USERNAME, env.DOCKER_IMAGE_NAME) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 